# Generated by Django 5.0.6 on 2024-06-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
