# Generated by Django 5.0.6 on 2024-06-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_orders_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
