# Generated by Django 5.0.6 on 2024-06-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='count',
            new_name='quantity',
        ),
    ]
