# Generated by Django 5.0.6 on 2024-06-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_wishlist_wishlistitems_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitems',
            name='quantity',
        ),
    ]
