# Generated by Django 5.0.6 on 2024-06-16 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
