# Generated by Django 5.0.6 on 2024-06-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_cartitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='price',
        ),
    ]
