# Generated by Django 5.0.6 on 2024-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_cartitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcodes',
            name='title',
            field=models.CharField(default='discount', max_length=12),
        ),
    ]
