# Generated by Django 5.0.6 on 2024-06-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_usertype_alter_profile_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='seller',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.usertype'),
        ),
    ]
