# Generated by Django 5.0.6 on 2024-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_profile_seller_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
