# Generated by Django 5.0.6 on 2024-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='is_seller',
            field=models.BooleanField(),
        ),
    ]
